name: Build Docker Container

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: src/SmtpPilot/Dockerfile
          tags: smtppilot:latest
          username: ${{ secrets.REGISTRY_TOKEN }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          registry: ${{ secrets.REGISTRY }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}